language: ruby
services: docker

script:
  # no actual tests (chefspec might be implemented in future)
  - /bin/true

before_deploy:
  # Test-kitchen run
  - cp -f .travis-kitchen.yml .kitchen.yml
  - bundle exec kitchen converge ubuntu-1604
  - sleep 10 && bundle exec kitchen verify ubuntu-1604

deploy:
  provider: script
  script: bash .publish.sh
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]
